### ISSUE TITLE
cursor in GUI is almost invisible

### ISSUE THREAD

**Issue by habamax** [kkga/vim-envy#1]
![image](https://user-images.githubusercontent.com/234774/98470085-772b5f00-21f4-11eb-80ce-624ff4b73781.png)

**Comment by kkga** [comment]
Thanks for the first issue 😅

I've never used GUI vim, but I'm gonna test it out later today.

The cursor is black with both `tgc` and `notgc` in a terminal on my end.

Since you're a seasoned colorscheme maker: is there any special highlight group for cursor in GUI?

(Also: thanks for godot-vim btw)

**Comment by habamax** [comment]
> The cursor is black with both tgc and notgc in a terminal on my end.

Terminals usually have have their own cursor color setup and vim colorscheme can't change it.

> Since you're a seasoned colorscheme maker: is there any special highlight group for cursor in GUI?

It is `Cursor`. There is also `lCursor` for the cursor color when a keymap is activated.

> (Also: thanks for godot-vim btw)

You're welcome!

**Comment by kkga** [comment]
Should be fixed now. Looks like GUIs treat cursor in a special way, so I'll need to revisit all vim/nvim+tui/gui combinations to make sure they're consistent.
